branch: master
check:
- kpande_AWS_1652454805080
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework:
- all
secrets-scan-file-type: []
